[workspace]
members = [
  "hourai",
  "hourai-feeds",
  "hourai-logger",
  "hourai-music",
  "hourai-validation",
  #"hourai-web",
  "storage/sql",
  "storage/redis",
]

[profile.release]
opt-level = 3
lto = true
