[workspace]
members = [
  "hourai",
  "hourai-feeds",
  #"hourai-frontend",
  "hourai-logger",
  "hourai-music",
  "hourai-verification",
  "hourai-web",
  "storage/common",
  "storage/sql",
  "storage/redis",
]

[profile.release]
opt-level = 3
lto = true
